#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_assets.py — Icon/Logo embedding script

Build sırasında calistirilir:
  python build_tools/gen_assets.py

Icon/ ve Logom/big_logo/ icindeki tum PNG ve ICO dosyalarini okur,
base64 olarak core/_icons.py'ye yazar.

Nuitka bu dosyayi derleyince tum assetler exe icine gomulur —
Program Files'ta hicbir Image/Logo klasoru gorunmez.
"""

import base64
import os
import sys

_HERE    = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(_HERE)
OUT_FILE = os.path.join(ROOT_DIR, 'core', '_icons.py')

ASSET_SOURCES = [
    # Tum Icon/ klasoru — kucuk ikonlar + modul gorsel assetleri
    os.path.join(ROOT_DIR, 'Icon'),
]

# Logom/ icinden sadece runtime'da kullanilan dosyalar (tek tek eklenir)
LOGOM_SPECIFIC = [
    os.path.join(ROOT_DIR, 'Logom', 'big_logo', 'sidebarlogo.png'),   # sidebar logo
    os.path.join(ROOT_DIR, 'Logom', 'big_logo', 'ContraCore.png'),    # compare-191 header logo
]

INCLUDE_EXTS = {'.png', '.ico'}


def _collect_assets() -> dict:
    """Returns {name: bytes} for all found assets (flat names, no path)."""
    assets = {}

    # Icon/ klasorunden tum PNG/ICO dosyalari
    for src_dir in ASSET_SOURCES:
        if not os.path.isdir(src_dir):
            print(f'[WARN] Klasor bulunamadi, atlaniyor: {src_dir}')
            continue
        for fname in os.listdir(src_dir):
            ext = os.path.splitext(fname)[1].lower()
            if ext not in INCLUDE_EXTS:
                continue
            fpath = os.path.join(src_dir, fname)
            if not os.path.isfile(fpath):
                continue
            if fname in assets:
                continue  # first occurrence wins
            with open(fpath, 'rb') as f:
                assets[fname] = f.read()

    # Logom/ icinden sadece belirtilen spesifik dosyalar
    for fpath in LOGOM_SPECIFIC:
        if not os.path.isfile(fpath):
            print(f'[WARN] Logom dosyasi bulunamadi: {fpath}')
            continue
        fname = os.path.basename(fpath)
        if fname not in assets:
            with open(fpath, 'rb') as f:
                assets[fname] = f.read()

    return assets


def generate(out_path: str = OUT_FILE):
    assets = _collect_assets()
    if not assets:
        print('[HATA] Hic asset bulunamadi!')
        sys.exit(1)

    total_kb = sum(len(v) for v in assets.values()) // 1024

    lines = [
        '# AUTO-GENERATED by build_tools/gen_assets.py — do not edit manually',
        '# Regenerated on every build.',
        'import base64',
        'from PySide6.QtGui import QPixmap',
        '',
        '_DATA: dict[str, bytes] = {',
    ]

    for name, data in sorted(assets.items()):
        b64 = base64.b64encode(data).decode('ascii')
        lines.append(f'    {name!r}: base64.b64decode(')
        # Split long base64 strings into 76-char chunks for readability
        chunks = [b64[i:i+76] for i in range(0, len(b64), 76)]
        for i, chunk in enumerate(chunks):
            comma = '' if i < len(chunks) - 1 else ''
            lines.append(f'        {chunk!r}')
        lines.append('    ),')

    lines += [
        '}',
        '',
        '',
        'def load(name: str) -> QPixmap:',
        '    """Returns a QPixmap loaded from embedded bytes. Empty QPixmap if not found."""',
        '    pix = QPixmap()',
        '    data = _DATA.get(name)',
        '    if data:',
        '        pix.loadFromData(data)',
        '    return pix',
        '',
    ]

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'[OK] core/_icons.py uretildi: {len(assets)} asset, ~{total_kb} KB raw')
    for name in sorted(assets):
        print(f'     {name}  ({len(assets[name]) // 1024} KB)')


if __name__ == '__main__':
    generate()
